### PR TITLE
Use memory sizes and offsets, not file sizes and file offsets on Linux

### LINKED ISSUE #50: Segmentation fault in SharedLibrary::id()
Hi, I am using this library inside Sentry plugin, but it causes segmentation fault in `SharedLibrary::id()` method.

Minimal reproduce example:

```rust
use findshlibs::{SharedLibrary, TargetSharedLibrary};

fn main() {
    TargetSharedLibrary::each(|shlib| {
        println!("{:?}", shlib.name());
        println!("{:?}", shlib.id());
    });
}
```

```
# cargo run
   Compiling source v0.1.0 (/source)
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/source`
"/source/target/debug/source"
Some(GnuBuildId("de96a0646f83a1168afdadd4244468dad9e720e1"))
"linux-vdso.so.1"
Segmentation fault (core dumped)
```

Relevant output from gdb:

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555555b492 in <findshlibs::linux::SharedLibrary as findshlibs::SharedLibrary>::id (self=0x7fffffffdf98) at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/findshlibs-0.5.0/src/linux/mod.rs:237
237	                    offset += nhdr.n_namesz as usize;
```

Debug output for `linux-vdso.so.1`:

```
SharedLibrary { 
    size: 64, 
    addr: 0x7ffcde691000, 
    name: "linux-vdso.so.1", 
    headers: [
        Phdr { p_type: 1, p_flags: 5, p_offset: 0, p_vaddr: 18446744073700114432, p_paddr: 18446744073700114432, p_filesz: 3693, p_memsz: 3693, p_align: 4096 }, 
        Phdr { p_type: 2, p_flags: 4, p_offset: 1080, p_vaddr: 18446744073700115512, p_paddr: 18446744073700115512, p_filesz: 240, p_memsz: 240, p_align: 8 }, 
        Phdr { p_type: 4, p_flags: 4, p_offset: 768, p_vaddr: 18446744073700115200, p_paddr: 18446744073700115200, p_filesz: 60, p_memsz: 60, p_align: 4 }, 
        Phdr { p_type: 1685382480, p_flags: 4, p_offset: 828, p_vaddr: 18446744073700115260, p_paddr: 18446744073700115260, p_filesz: 44, p_memsz: 44, p_align: 4 }
    ] 
}
```

I can provide more info if you need.

## Versions

* findshlibs 0.5.0
* Rust compiler 1.40.0
* Ubuntu 18.04 in Docker container inside Centos 7

### PR DESCRIPTION
**Pull request by fitzgen**
In the `SharedLibrary::id` method on Linux, we were mistakenly using file sizes
and offsets when searching through the notes structures in the PT_NOTE
segment. This corrects that issue to use the fields in phdr et al that are
explicitly for memory offsets and sizes.

Fixes #50

cc @JakubOnderka -- I haven't actually been able to reproduce #50 on my machine, can you test this out and verify whether it fixes the issue?

### CODE REVIEW

File: src/linux/mod.rs [hunk 1]
```diff
@@ -204,6 +204,11 @@ impl<'a> SharedLibrary<'a> {
             }
         }
     }
+
+    fn program_header_vm_addr(&self, phdr: &Phdr) -> *const u8 {
+        let addr = (self.addr as usize) + (phdr.p_vaddr as usize);
+        addr as *const u8
```
Comment (philipc) [inline src/linux/mod.rs]: This function doesn't seem useful to me. There's a single caller that is already accessing a related field (`phdr.p_memsz`), and it immediately casts the result back to a usize.

Maybe if it would be more useful as an unsafe function that returned `&[u8]`, but that would also require rewriting the note processing to use a slice instead of pointers.

File: src/linux/mod.rs [hunk 2]
```diff
@@ -238,23 +247,33 @@ impl<'a> SharedLibraryTrait for SharedLibrary<'a> {
...
                     // been observed in practice.
-                    let nhdr = &*((self.addr as usize + offset) as *const Nhdr32);
-                    offset += mem::size_of_val(nhdr);
-                    offset += nhdr.n_namesz as usize;
-                    align(alignment, &mut offset);
-                    let value =
-                        slice::from_raw_parts(self.addr.add(offset), nhdr.n_descsz as usize);
-                    offset += nhdr.n_descsz as usize;
-                    align(alignment, &mut offset);
+                    let nhdr = (note_header_addr as *const Nhdr32).as_ref().unwrap();
```
Comment (philipc) [inline src/linux/mod.rs]: This doesn't check that there are still enough bytes left for the header (and similar for name/desc below). Not sure how pedantic we need to be here, but this is the kind of thing that would be easier to check if we used a slice.

**Comment by JakubOnderka** [comment]
Still don't work, but now with different error:

```
"linux-vdso.so.1"
thread 'main' panicked at 'attempt to add with overflow', src/linux/mod.rs:209:20
```

Line 209 is:

```rust
let addr = (self.addr as usize) + (phdr.p_vaddr as usize);
```

So I add debug output before that line for both variables:

```
addr: 0x7ffcda6f9000
phdr.p_vaddr: ffffffffff700300
```

**Comment by fitzgen** [comment]
Ok, new version up that uses slices and safer primitive operations.

@JakubOnderka, I'm not sure what's up with those `addr` and `p_vaddr` values, but I think this new version should at least not crash on them, even if it can't find the actual id.

I'm also a little unsure about the alignment behavior we already had here, but I've preserved it. If we're still getting garbage here, then it may be worth revisiting what readelf is doing and making sure that we're matching its behavior. `elf.h` is really not giving us enough docs here...

File: src/linux/mod.rs [hunk 3]
```diff
@@ -41,14 +42,96 @@ pub struct Segment<'a> {
...
+        &self,
+        shlib: &SharedLibrary<'a>,
+    ) -> impl Iterator<Item = (libc::Elf32_Word, &'a [u8], &'a [u8])> {
+        assert!(self.is_note());
+
+        let phdr = self.phdr();
+
+        let alignment = std::cmp::min(phdr.p_align as usize, 4);
+        let align = move |data: &'a [u8]| {
+            // Same logic as in `gimli` which took it from `readelf`.
```
Comment (philipc) [inline src/linux/mod.rs]: Move this comment above the `min`, since that is part of the logic too, and move this `if` outside of the closure, because it only needs to be checked once.
```suggestion
            // Same logic as in `goblin` which took it from `readelf`.
```

File: src/linux/mod.rs [hunk 4]
```diff
@@ -41,14 +42,96 @@ pub struct Segment<'a> {
...
             }
-        }
+
+            let ptr = data.as_ptr() as usize;
+            let diff = ptr % alignment;
+            if diff <= data.len() {
+                Some(&data[diff..])
+            } else {
+                None
+            }
```
Comment (philipc) [inline src/linux/mod.rs]: This is missing the step to compute `alignment - diff`, and `slice::get` can make this simpler, so replace this with `data.get(alignment - diff..)`.

File: src/linux/mod.rs [hunk 5]
```diff
@@ -41,14 +42,96 @@ pub struct Segment<'a> {
...
+            let nhdr = (data.as_ptr() as *const Nhdr32).as_ref().unwrap();
+            data = &data[nhdr_size..];
+
+            // It is followed by a name of size `n_namesz`.
+            let name_size = nhdr.n_namesz as usize;
+            if data.len() < name_size {
+                data = &[];
+                return None;
+            }
+            let name = &data[..name_size];
```
Comment (philipc) [inline src/linux/mod.rs]: These 5 lines are similar to `let name = data.get(..name_size)?;`, with the difference being that it doesn't set `data = &[]` on error, but then the `align` below doesn't set `data = &[]` on error either so does that difference matter?

File: src/linux/mod.rs [hunk 6]
```diff
@@ -41,14 +42,96 @@ pub struct Segment<'a> {
...
+    ///
+    /// 1. The `NT_*` note type.
+    /// 2. The note name.
+    /// 3. The note descriptor payload.
+    ///
+    /// You must pass this segment's `SharedLibrary` or else this is wild UB.
+    unsafe fn notes(
+        &self,
+        shlib: &SharedLibrary<'a>,
+    ) -> impl Iterator<Item = (libc::Elf32_Word, &'a [u8], &'a [u8])> {
```
Comment (philipc) [inline src/linux/mod.rs]: Nice use of `impl Iterator`. I hadn't seen `iter::from_fn` before.

File: src/linux/mod.rs (hunk 3 above)
Comment (fitzgen) [reply src/linux/mod.rs]: This closure should get inlined, and then only checked once. The problem with trying to explicitly only check it once is that `alignment` would need to become an `Option<usize>` and then we would be checking the option discriminant, which is equivalent, so it doesn't really buy us anything.

File: src/linux/mod.rs (hunk 4 above)
Comment (philipc) [reply src/linux/mod.rs]: And it needs the `diff != 0` too.

**Comment by fitzgen** [comment]
Ok, this version matches `readelf` for everything I've been able to throw at it. I think I've also addressed everything from your review, @philipc.

Care to retest @JakubOnderka?

**Comment by JakubOnderka** [comment]
@fitzgen Now it works, thank you very much!

**Comment by fitzgen** [comment]
Thanks for re-testing @JakubOnderka and thanks for review @philipc!
